<?php

namespace AppBundle\Repository;

/**
 * InsultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsultRepository extends \Doctrine\ORM\EntityRepository
{
}
