app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:
    path: /
    defaults: { _controller: AppBundle:Home:index }

create:
    path:      /create
    defaults:  { _controller: AppBundle:Admin:create }

edit:
    path:      /edit/{id}
    defaults:  { _controller: AppBundle:Home:edit }


generate:
    path: /generate
    defaults: { _controller: AppBundle:Home:generate }