app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:
    path: /
    defaults: { _controller: AppBundle:Home:index }

insult:
    path: /insult
    defaults: { _controller: AppBundle:Home:insult }