<?php

namespace AppBundle\Repository\Product;

/**
 * indexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class indexRepository extends \Doctrine\ORM\EntityRepository
{
}
